/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  %FILE_NAME%
 *  model: %MODEL_NAME%
 *  expmt: %EXPERIMENT_NAME%
 *  date:  %GENERATION_DATE%
 *  time:  %GENERATION_TIME%
 *  user:  %USER_NAME%
 *  from:  %COMPANY_NAME%
 *  build: %GENERATION_BUILD%
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently only Euler, RungeKutta2 and RungeKutta4 are supplied,
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef XX_INTEG_H
#define XX_INTEG_H

/* 20-sim include files */
#include "xxtypes.h"
#include "xxmodel.h" /* For the XXModelInstance typedef */

/* the integration methods */
#ifdef Discrete_METHOD
void %FUNCTIONPREFIX%DiscreteInitialize (%VARPREFIX%ModelInstance* model_instance);
void %FUNCTIONPREFIX%DiscreteTerminate (%VARPREFIX%ModelInstance* model_instance);
void %FUNCTIONPREFIX%DiscreteStep (%VARPREFIX%ModelInstance* model_instance);
#endif 

#ifdef Euler_METHOD
void %FUNCTIONPREFIX%EulerInitialize (%VARPREFIX%ModelInstance* model_instance);
void %FUNCTIONPREFIX%EulerTerminate (%VARPREFIX%ModelInstance* model_instance);
void %FUNCTIONPREFIX%EulerStep (%VARPREFIX%ModelInstance* model_instance);
#endif 

#ifdef RungeKutta2_METHOD
void %FUNCTIONPREFIX%RungeKutta2Initialize (%VARPREFIX%ModelInstance* model_instance);
void %FUNCTIONPREFIX%RungeKutta2Terminate (%VARPREFIX%ModelInstance* model_instance);
void %FUNCTIONPREFIX%RungeKutta2Step (%VARPREFIX%ModelInstance* model_instance);
#endif

#ifdef RungeKutta4_METHOD
void %FUNCTIONPREFIX%RungeKutta4Initialize (%VARPREFIX%ModelInstance* model_instance);
void %FUNCTIONPREFIX%RungeKutta4Terminate (%VARPREFIX%ModelInstance* model_instance);
void %FUNCTIONPREFIX%RungeKutta4Step (%VARPREFIX%ModelInstance* model_instance);
#endif

#endif
