/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  %FILE_NAME%
 *  model: %MODEL_NAME%
 *  expmt: %EXPERIMENT_NAME%
 *  date:  %GENERATION_DATE%
 *  time:  %GENERATION_TIME%
 *  user:  %USER_NAME%
 *  from:  %COMPANY_NAME%
 *  build: %GENERATION_BUILD%
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   XXDouble %VARPREFIX%variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXString %VARPREFIX%variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void %FUNCTIONPREFIX%CalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>

#include <string.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxfuncs.h"
%IF%%NUMBER_MATRICES%
#include "xxmatrix.h"
%ENDIF%
%IF%%NUMBEROF_DLL_MotionProfiles%
#include "MotionProfiles.h"
%ENDIF%
%IF%%NUMBEROF_DLL_EulerAngles%
#include "EulerAngles.h"
%ENDIF%
%IF%%NUMBEROF_DELAYFUNCTION%
#include <string.h> /* memcpy */
%ENDIF%
%IF%%NUMBEROF_DLL_Table2D%
#include "xxTable2D.h"
%ENDIF%
%IF%%NOT(EQ(INTEGRATION_METHOD_NAME,MeBDFi))%
%IF%%NUMBER_DEPSTATES%
#if defined _MSC_VER
#pragma message("Warning: This model contains dependent states. Dependent states solving is not implemented in this code generation template.")
#elif defined __GNUC__
#warning This model contains dependent states. Dependent states solving is not implemented in this code generation template..
#endif
%ENDIF%
%IF%%NUMBER_ALGLOOPS%
#if defined _MSC_VER
#pragma message("Warning: This model contains algebraic loops. Algebraic loop solving is not implemented in this code generation template.")
#elif defined __GNUC__
#warning This model contains algebraic loops. Algebraic loop solving is not implemented in this code generation template.
#endif
%ENDIF%
%IF%%NUMBER_CONSTRAINTS%
#if defined _MSC_VER
#pragma message("Warning: This model contains constraint variables. Constraint variable solving is not implemented in this code generation template.")
#elif defined __GNUC__
#warning This model contains constraint variables. Constraint variable solving is not implemented in this code generation template.
#endif
%ENDIF%
%ENDIF%

%IF%%NUMBEROF_DLL_Table2D%
/* The path to the extracted resource folder location provided by the
 * co-simulation engine for the currently active FMU instance
 */
const char* g_fmuResourceLocation = NULL;
%ENDIF%

/**
 * Convert an uri provided by the the co-simulator to a native path
 * @param uri Input path. native and file:/ and file:/// uri's right now
 * @return Natve path that ends with a path separator.
 * Note that the caller is responsible for free-ing the allocated string buffer
 * memory
 * defined in %FMI_PREFIX%Functions.c
 */
extern const char* URIToNativePath(%VARPREFIX%ModelInstance* model_instance, const char* uri);

XXBoolean %FUNCTIONPREFIX%ModelInstance_Constructor(%VARPREFIX%ModelInstance* model_instance,
													%FMI_PREFIX%String instanceName,
%IF%%EQ(FMIVERSION,2.0)%
													%FMI_PREFIX%Type fmuType,
													%FMI_PREFIX%String fmuResourceLocation,
%ENDIF%
%IF%%EQ(FMIVERSION,1.0)%
													fmiCallbackFunctions fmi_functions)
%ENDIF%
%IF%%EQ(FMIVERSION,2.0)%
													const fmi2CallbackFunctions *functions)
%ENDIF%
{
	int offset = 0;

%IF%%EQ(FMIVERSION,1.0)%
	fmiCallbackFunctions *functions = &fmi_functions;
%ENDIF%

	/* initialize the members of the model_instance structure */
	model_instance->instanceName = (%FMI_PREFIX%String) functions->allocateMemory(1 + strlen(instanceName), sizeof(char));

	if (!model_instance->instanceName)
	{
		functions->logger(NULL, instanceName, %FMI_PREFIX%Error, "error",
			"%FMI_PREFIX%Instantiate: Out of memory while allocating instance name");
		return XXFALSE;
	}
	strcpy((char *)model_instance->instanceName, (char *)instanceName);

	/* Prepare the model instance struct */
	model_instance->start_time = %START_TIME%;
	model_instance->finish_time = 0.0;
	model_instance->m_use_finish_time = XXFALSE;
	model_instance->step_size = %TIME_STEP_SIZE%;
	model_instance->time = 0.0;
	model_instance->steps = 0;
	model_instance->%XX_INITIALIZE% = XXTRUE;
	model_instance->major = XXTRUE;
	model_instance->stop_simulation = XXFALSE;
	model_instance->m_reinitState = XXFALSE;
	model_instance->m_initState = XXFALSE;

	/* Set the offsets within the model_instance->MEMORY array */
%IF%%NUMBER_CONSTANTS%
	model_instance->%XX_CONSTANT_ARRAY_NAME% = &model_instance->MEMORY[offset]; /* constants offset */
	offset = offset + %VARPREFIX%constants_count;
%ENDIF%
%IF%%NUMBER_PARAMETERS%
	model_instance->%XX_PARAMETER_ARRAY_NAME% = &model_instance->MEMORY[offset];	/* parameters offset */
	offset = offset + %VARPREFIX%parameter_count;
%ENDIF%
%IF%%NUMBER_INITIAL_VALUES%
	model_instance->%XX_INITIAL_VALUE_ARRAY_NAME% = &model_instance->MEMORY[offset];	/* initial values offset */
	offset = offset + %VARPREFIX%initialvalue_count;
%ENDIF%
%IF%%NUMBER_VARIABLES%
	model_instance->%XX_VARIABLE_ARRAY_NAME% = &model_instance->MEMORY[offset];	/* variables offset */
	offset = offset + %VARPREFIX%variable_count;
%ENDIF%
%IF%%NUMBER_STATES%
	model_instance->%XX_STATE_ARRAY_NAME% = &model_instance->MEMORY[offset];	/* states offset */
	offset = offset + %VARPREFIX%state_count;
	model_instance->%XX_RATE_ARRAY_NAME% = &model_instance->MEMORY[offset];	/* rates offset */
	offset = offset + %VARPREFIX%state_count;
%ENDIF%
%IF%%NUMBER_DEPSTATES%
	model_instance->%XX_DEP_STATE_ARRAY_NAME% = &model_instance->MEMORY[offset];	/* states offset */
	offset = offset + %VARPREFIX%depstate_count;
	model_instance->%XX_DEP_RATE_ARRAY_NAME% = &model_instance->MEMORY[offset];	/* rates offset */
	offset = offset + %VARPREFIX%depstate_count;
%ENDIF%
%IF%%NUMBER_ALGLOOPS%
	model_instance->%XX_ALG_IN_ARRAY_NAME% = &model_instance->MEMORY[offset];	/* aglebraic loop input offset */
	offset = offset + %VARPREFIX%algloop_count;
	model_instance->%XX_ALG_OUT_ARRAY_NAME% = &model_instance->MEMORY[offset];	/* aglebraic loop output offset */
	offset = offset + %VARPREFIX%algloop_count;
%ENDIF%
%IF%%NUMBER_CONSTRAINTS%
	model_instance->%XX_ALG_IN_ARRAY_NAME% = &model_instance->MEMORY[offset];		/* constraint in offset */
	offset = offset + %VARPREFIX%constraint_count;
	model_instance->%XX_ALG_OUT_ARRAY_NAME% = &model_instance->MEMORY[offset];		/* constraint out offset */
%ENDIF%

	/* Register the callback */
%IF%%EQ(FMIVERSION,1.0)%
	model_instance->fmiCallbackFunctions = fmi_functions;

	/* Remember the resource folder location */
	model_instance->resourceLocation = NULL;
%ENDIF%
%IF%%EQ(FMIVERSION,2.0)%
	model_instance->fmiCallbackFunctions = functions;

	/* Remember the resource folder location */
	model_instance->resourceLocation = URIToNativePath(model_instance, fmuResourceLocation);
%ENDIF%

%IF%%EQ(FMIVERSION,2.0)%
	/* check if we are setup for co-simulation, that's the only possible option for now */
	if( fmuType != %FMI_PREFIX%CoSimulation )
	{
		model_instance->fmiCallbackFunctions->logger(NULL, instanceName, %FMI_PREFIX%Error, "error",
			"FMU can only be used for Co-Simulation, not for Model Exchange");
		return XXFALSE;
	}
%ENDIF%
	return XXTRUE;
}

#if (%NUMBER_PARAMETERS% > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
/* this method is called before calculation is possible */
void %FUNCTIONPREFIX%ModelInitialize (%VARPREFIX%ModelInstance* model_instance)
{
%IF%%NUMBER_CONSTANTS%
	/* set the constants */
%INITIALIZE_CONSTANTS%

%ENDIF%
%IF%%NUMBER_PARAMETERS%
	/* set the parameters */
%INITIALIZE_PARAMETERS%

%ENDIF%
%IF%%NUMBER_INITIAL_VALUES%
	/* set the initial values */
%INITIALIZE_INITIAL_VALUES%

%ENDIF%
%IF%%NUMBER_STATES%
	/* set the states */
%INITIALIZE_STATES%

%ENDIF%
%IF%%NUMBER_MATRICES%
	/* set the matrices */
%INITIALIZE_MATRICES%

%ENDIF%
%IF%%OR(NUMBER_FAVORITE_PARAMETERS,NUMBER_FAVORITE_VARIABLES)%
	/* set the favorites */
%INITIALIZE_FAVORITE_PARS%
%INITIALIZE_FAVORITE_VARS%
%ENDIF%
}
#if (%NUMBER_PARAMETERS% > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void %FUNCTIONPREFIX%CalculateInitial (%VARPREFIX%ModelInstance* model_instance)
{
%IF%%NUMBEROF_DLL_Table2D%
	/* Make sure that the Table2D initialization function can find the resource
	 * location for this FMU instance
	 */
	g_fmuResourceLocation = model_instance->resourceLocation;

%ENDIF%
%IF%%NUMBER_FAVORITE_PARAMETERS%
	/* the favorite parameters equations */
%FAVORITE_PARS_EQUATIONS%

%ENDIF%
%INITIAL_EQUATIONS%

%IF%%NUMBER_STATES%
	/* set the states */
%INITIALIZE_STATES%

%ENDIF%
}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void %FUNCTIONPREFIX%CalculateStatic (%VARPREFIX%ModelInstance* model_instance)
{
%IF%%NUMBEROF_DLL_Table2D%
	/* Make sure that the Table2D initialization function can find the resource
	 * location for this FMU instance
	 */
	g_fmuResourceLocation = model_instance->resourceLocation;

%ENDIF%
%STATIC_EQUATIONS%
}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void %FUNCTIONPREFIX%CalculateInput (%VARPREFIX%ModelInstance* model_instance)
{
%IF%%NUMBEROF_DLL_Table2D%
	/* Make sure that the Table2D initialization function can find the resource
	 * location for this FMU instance
	 */
	g_fmuResourceLocation = model_instance->resourceLocation;

%ENDIF%
%IF%%NUMBER_FAVORITE_PARAMETERS%
	/* the favorite parameters equations */
%FAVORITE_PARS_EQUATIONS%

%ENDIF%
%INPUT_EQUATIONS%
}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void %FUNCTIONPREFIX%CalculateDynamic (%VARPREFIX%ModelInstance* model_instance)
{
%IF%%NUMBEROF_DLL_Table2D%
	/* Make sure that the Table2D initialization function can find the resource
	 * location for this FMU instance
	 */
	g_fmuResourceLocation = model_instance->resourceLocation;

%ENDIF%
%DYNAMIC_EQUATIONS%

	/* increment the step counter */
	model_instance->steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void %FUNCTIONPREFIX%CalculateOutput (%VARPREFIX%ModelInstance* model_instance)
{
%IF%%NUMBEROF_DLL_Table2D%
	/* Make sure that the Table2D initialization function can find the resource
	 * location for this FMU instance
	 */
	g_fmuResourceLocation = model_instance->resourceLocation;

%ENDIF%
%OUTPUT_EQUATIONS%
%IF%%NUMBEROF_DELAYFUNCTION%
	/* delay update */
	%FUNCTIONPREFIX%DelayUpdate(model_instance);

%ENDIF%
%IF%%NUMBER_FAVORITE_VARIABLES%
	/* set the favorite variables */
%FAVORITE_VARS_EQUATIONS%
%ENDIF%
}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void %FUNCTIONPREFIX%CalculateFinal (%VARPREFIX%ModelInstance* model_instance)
{
%IF%%NUMBEROF_DLL_Table2D%
	/* Make sure that the Table2D initialization function can find the resource
	 * location for this FMU instance
	 */
	g_fmuResourceLocation = model_instance->resourceLocation;

%ENDIF%
%FINAL_EQUATIONS%
}

/* this method is called after all calculations are performed */
void %FUNCTIONPREFIX%ModelTerminate(%VARPREFIX%ModelInstance* model_instance)
{
}

%IF%%NUMBEROF_DELAYFUNCTION%
void %FUNCTIONPREFIX%DelayUpdate(%VARPREFIX%ModelInstance* model_instance)
{
	memcpy(model_instance->delay_update_array, model_instance->delay_last_values, %VARPREFIX%delay_count * sizeof(XXDouble));
}

XXDouble %FUNCTIONPREFIX%ModelDelay (%VARPREFIX%ModelInstance* model_instance, XXDouble argument1, XXDouble argument2, XXInteger id)
{
	XXDouble value;

	if (model_instance->%XX_INITIALIZE%)
	{
		value = argument2;
	}
	else
	{
		value = model_instance->delay_update_array[id];
	}

	if (model_instance->major)
	{
		model_instance->delay_last_values[id] = argument1;
	}

	return value;
}

%ENDIF%
%IF%%NUMBEROF_INITIALFUNCTION%
XXDouble %FUNCTIONPREFIX%ModelInitialValue (%VARPREFIX%ModelInstance* model_instance, XXDouble argument, XXInteger identifier)
{
	/* The storage array '%VARPREFIX%initial_value_array' is declared in xxmodel.c because its size is model dependent */
	XXDouble value;

	if (model_instance->%XX_INITIALIZE%)
	{
		value = argument;
		model_instance->initial_value_array[identifier] = value;
	}
	else
	{
		value = model_instance->initial_value_array[identifier];
	}
	return value;
}

%ENDIF%
%IF%%NUMBEROF_WARNSTATEMENT%
XXBoolean %FUNCTIONPREFIX%ModelWarning (%VARPREFIX%ModelInstance* model_instance, XXString message, XXInteger id)
{
	if (model_instance == NULL)
		return 0;

%IF%%FMI1%
	if(model_instance->fmiCallbackFunctions.logger != NULL)
	{
		model_instance->fmiCallbackFunctions.logger(NULL, "%SUBMODEL_NAME%", fmiWarning, "warning", message);
	}
%ENDIF%
%IF%%FMI2%
	if(model_instance->fmiCallbackFunctions != NULL && model_instance->fmiCallbackFunctions->logger != NULL)
	{
		model_instance->fmiCallbackFunctions->logger(NULL, "%SUBMODEL_NAME%", %FMI_PREFIX%Warning, "warning", message);
	}
%ENDIF%
	return 0;
}

%ENDIF%
%IF%%NUMBEROF_STOPSTATEMENT%
XXBoolean %FUNCTIONPREFIX%ModelStopSimulation (%VARPREFIX%ModelInstance* model_instance, XXString message, XXInteger id)
{
	if (model_instance == NULL)
		return 0;

	model_instance->stop_simulation = XXTRUE;

%IF%%FMI1%
	if(model_instance->fmiCallbackFunctions.logger != NULL)
	{
		model_instance->fmiCallbackFunctions.logger(NULL, "%SUBMODEL_NAME%", fmiError, "error", message);
	}
%ENDIF%
%IF%%FMI2%
	if(model_instance->fmiCallbackFunctions != NULL && model_instance->fmiCallbackFunctions->logger != NULL)
	{
		model_instance->fmiCallbackFunctions->logger(NULL, "%SUBMODEL_NAME%", %FMI_PREFIX%Error, "error", message);
	}
%ENDIF%
	return 0;
}

%ENDIF%
%IF%%NUMBEROF_EVENTFUNCTION%
XXBoolean %FUNCTIONPREFIX%ModelEvent (%VARPREFIX%ModelInstance* model_instance, XXDouble argument, XXInteger id)
{
	if (model_instance->major)
	{
		XXDouble prevValue = model_instance->event[id];
		model_instance->event[id] = argument;
		if ( ((argument <= 0.0) && (prevValue > 0.0)) ||
			 ((argument >= 0.0) && (prevValue < 0.0)) )
		{
			return XXTRUE;
		}
	}
	return XXFALSE;
}

%ENDIF%
%IF%%NUMBEROF_EVENTUPFUNCTION%
XXBoolean %FUNCTIONPREFIX%ModelEventUp (%VARPREFIX%ModelInstance* model_instance, XXDouble argument, XXInteger id)
{
	if (model_instance->major)
	{
		XXDouble prevValue = model_instance->event_up[id];
		model_instance->event_up[id] = argument;
		if ((argument >= 0.0) && (prevValue < 0.0))
		{
			return XXTRUE;
		}
	}
	return XXFALSE;
}

%ENDIF%
%IF%%NUMBEROF_EVENTDOWNFUNCTION%
XXBoolean %FUNCTIONPREFIX%ModelEventDown (%VARPREFIX%ModelInstance* model_instance, XXDouble argument, XXInteger id)
{
	if (model_instance->major)
	{
		XXDouble prevValue = model_instance->event_down[id];
		model_instance->event_down[id] = argument;
		if ((argument <= 0.0) && (prevValue > 0.0))
		{
			return XXTRUE;
		}
	}
	return XXFALSE;
}

%ENDIF%
%IF%%NUMBEROF_TIMEEVENTFUNCTION%
XXBoolean %FUNCTIONPREFIX%ModelTimeEvent (%VARPREFIX%ModelInstance* model_instance, XXDouble argument, XXInteger id)
{
	if (model_instance->major)
	{
		XXDouble prevValue = model_instance->time_event[id];
		model_instance->time_event[id] = model_instance->time;
		if ((model_instance->time >= argument) && (prevValue < argument))
		{
			return XXTRUE;
		}
	}
	return XXFALSE;
}

%ENDIF%