/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  %FILE_NAME%
 *  subm:  %SUBMODEL_NAME%
 *  model: %MODEL_NAME%
 *  expmt: %EXPERIMENT_NAME%
 *  date:  %GENERATION_DATE%
 *  time:  %GENERATION_TIME%
 *  user:  %USER_NAME%
 *  from:  %COMPANY_NAME%
 *  build: %GENERATION_BUILD%
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxinteg.h"
#include "xxfuncs.h"
#include "xxsubmod.h"
#include "motionprofiles.h"
#include "EulerAngles.h"


/* The initialization function for submodel */
void %FUNCTIONPREFIX%InitializeSubmodel (XXDouble t)
{
	/* Initialization phase (allocating memory) */
	%VARPREFIX%%XX_INITIALIZE% = XXTRUE;
	%VARPREFIX%steps = 0;
	%FUNCTIONPREFIX%ModelInitialize ();
	%FUNCTIONPREFIX%%INTEGRATION_METHOD_NAME%Initialize ();

	/* Copy the time */
	%VARPREFIX%%XX_TIME% = t;

	/* Calculate the model for the first time */
	%FUNCTIONPREFIX%CalculateInitial ();
	%FUNCTIONPREFIX%CalculateStatic ();
	%FUNCTIONPREFIX%CalculateInput ();
	%FUNCTIONPREFIX%CalculateDynamic ();
	%FUNCTIONPREFIX%CalculateOutput ();

	/* End of initialization phase */
	%VARPREFIX%%XX_INITIALIZE% = XXFALSE;
}

/* The function that calculates the submodel */
void %FUNCTIONPREFIX%CalculateSubmodel (XXDouble t)
{
	/* Copy the time */
	%VARPREFIX%%XX_TIME% = t;

	/* Calculate the model */
	%FUNCTIONPREFIX%CalculateInput ();
	%FUNCTIONPREFIX%%INTEGRATION_METHOD_NAME%Step ();
	%FUNCTIONPREFIX%CalculateOutput ();
}

/* The termination function for submodel */
void %FUNCTIONPREFIX%TerminateSubmodel (XXDouble t)
{
	/* Copy the time */
	%VARPREFIX%%XX_TIME% = t;

	/* Calculate the final model equations */
	%FUNCTIONPREFIX%CalculateFinal ();

	/* and terminate the model itself (releasing memory) */
	%FUNCTIONPREFIX%ModelTerminate ();
	%FUNCTIONPREFIX%%INTEGRATION_METHOD_NAME%Terminate ();
}
