/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  %FILE_NAME%
 *  subm:  %SUBMODEL_NAME%
 *  model: %MODEL_NAME%
 *  expmt: %EXPERIMENT_NAME%
 *  date:  %GENERATION_DATE%
 *  time:  %GENERATION_TIME%
 *  user:  %USER_NAME%
 *  from:  %COMPANY_NAME%
 *  build: %GENERATION_BUILD%
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxinteg.h"
#include "xxfuncs.h"
#include "xxsubmod.h"
#include "motionprofiles.h"
#include "EulerAngles.h"


/* The initialization function for submodel */
void %FUNCTIONPREFIX%InitializeSubmodel (XXModelInstance* %VARPREFIX%model_instance, XXDouble t)
{
	/* Initialization phase (allocating memory) */
	%VARPREFIX%model_instance->%XX_INITIALIZE% = XXTRUE;
	%VARPREFIX%model_instance->steps = 0;
	%FUNCTIONPREFIX%ModelInitialize (%VARPREFIX%model_instance);
	%FUNCTIONPREFIX%%INTEGRATION_METHOD_NAME%Initialize (%VARPREFIX%model_instance);

	/* Copy the time */
	%VARPREFIX%model_instance->time = t;

	/* Calculate the model for the first time */
	%FUNCTIONPREFIX%CalculateInitial (%VARPREFIX%model_instance);
	%FUNCTIONPREFIX%CalculateStatic (%VARPREFIX%model_instance);
	%FUNCTIONPREFIX%CalculateInput (%VARPREFIX%model_instance);
	%FUNCTIONPREFIX%CalculateDynamic (%VARPREFIX%model_instance);
	%FUNCTIONPREFIX%CalculateOutput (%VARPREFIX%model_instance);

	/* End of initialization phase */
	%VARPREFIX%model_instance->%XX_INITIALIZE% = XXFALSE;
}

/* The function that calculates the submodel */
void %FUNCTIONPREFIX%CalculateSubmodel (XXModelInstance* %VARPREFIX%model_instance, XXDouble t)
{
	/* Copy the time */
	%VARPREFIX%model_instance->time = t;

	/* Calculate the model */
	%FUNCTIONPREFIX%CalculateInput (%VARPREFIX%model_instance);
	%FUNCTIONPREFIX%%INTEGRATION_METHOD_NAME%Step (%VARPREFIX%model_instance);
	%FUNCTIONPREFIX%CalculateOutput (%VARPREFIX%model_instance);
}

/* The termination function for submodel */
void %FUNCTIONPREFIX%TerminateSubmodel (XXModelInstance* %VARPREFIX%model_instance, XXDouble t)
{
	/* Copy the time */
	%VARPREFIX%model_instance->time = t;

	/* Calculate the final model equations */
	%FUNCTIONPREFIX%CalculateFinal (%VARPREFIX%model_instance);

	/* and terminate the model itself (releasing memory) */
	%FUNCTIONPREFIX%ModelTerminate (%VARPREFIX%model_instance);
	%FUNCTIONPREFIX%%INTEGRATION_METHOD_NAME%Terminate (%VARPREFIX%model_instance);
}
