/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  %FILE_NAME%
 *  model: %MODEL_NAME%
 *  expmt: %EXPERIMENT_NAME%
 *  date:  %GENERATION_DATE%
 *  time:  %GENERATION_TIME%
 *  user:  %USER_NAME%
 *  from:  %COMPANY_NAME%
 *  build: %GENERATION_BUILD%
 **********************************************************/

/* This file defines the functions necessary for table 2D lookup
   functions
*/
%IF%%NUMBEROF_DLL_Table2D%
#ifndef __TABLE2D_H
#define __TABLE2D_H

void Table2D_Initialize ();
void Table2D_Terminate ();

XXInteger Table2D_Table2DInit(XXDouble *inarr, XXInteger inputs, XXDouble *outarr, XXInteger outputs, XXInteger major);
XXInteger Table2D_TableRead(XXDouble *inarr, XXInteger inputs, XXDouble *outarr, XXInteger outputs, XXInteger major);

#endif  /* __TABLE2D_H */
%ELSE%
/* Empty file; no Table2D support needed for this model */
%ENDIF%
